### ISSUE TITLE
Compatibility issue with nwjs

### ISSUE THREAD

**Issue by hugoruscitti** [kmpm/node-mdns-js#30]
Hi!, i'm working in a new version of an nwjs application that uses mdns, but
when i publish a new service i get ``Uncaught Error: bind EADDRINUSE 0.0.0.0:5353``:

![index html 2015-01-16 14-34-02](https://cloud.githubusercontent.com/assets/99183/5780878/c97809cc-9d8c-11e4-8e0f-2bf4f002ee93.png)

**Comment by kmpm** [comment]
probably related to #31

**Comment by kmpm** [comment]
This should have been fixed but I don't have nwjs to test with.
Please reopen if it doesn't work.
