### ISSUE TITLE
Announced services doesn't show up in standard bonjour tools

### ISSUE THREAD

**Issue by auchenberg** [kmpm/node-mdns-js#33]
Hi,

I just tried switching to your pure JS implementation of MDNS, as I'm facing dependencies issues with the node-mdns package. Example:

```javascript
  var mdnsAnnouncement = mdns.createAdvertisement(mdns.tcp('remotedebug'), websocketAddress.port, {
    name: process.name || 'node-inspector app',
    txt: {
      description : 'app (via node-inspector)',
      type: 'app',
      id: 'node-inspector-process-' + process.pid,
      url: '',
      faviconUrl: faviconUrl,
      devtoolsFrontendUrl: frontendAddress.url,
      webSocketDebuggerUrl: websocketAddress.url
    }
  });

  mdnsAnnouncement.start();
```

When using your module to announce my service it doesn't show up in tools like [BonjourBrowser](http://www.tildesoft.com/) and [BonjourDumper](https://www.google.co.th/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0CBwQFjAA&url=https%3A%2F%2Fitunes.apple.com%2Fus%2Fapp%2Fbonjourdumper%2Fid670221310%3Fmt%3D12&ei=_djuVKizOJSOuASElYDACA&usg=AFQjCNGkwoFxr4tZXYGusbVBofrO0mC-pQ&sig2=dMULFQVnKMo08lfJ6u8iIg&bvm=bv.86956481,d.c2E&cad=rja).

So I'm wondering if this implementation compliant to the spec?

**Comment by auchenberg** [comment]
``mdns``:
![bonjour browser](https://cloud.githubusercontent.com/assets/173559/6388439/89fe9878-bdcc-11e4-8130-64a74b520e1c.png)

``mdns-js``:
![bonjour browser-1](https://cloud.githubusercontent.com/assets/173559/6388453/9f5d7e32-bdcc-11e4-8838-9c24253b778d.png)

**Comment by kmpm** [comment]
It's most likely a bug with this module.
For the moment I don't have time or resources to fix this but I will gladly accept a pull-request.

**Comment by auchenberg** [comment]
Alright. I don't have the insights into the MDNS to debug this further, but let's see if someone else can pitch in, and help out.

**Comment by kmpm** [comment]
Nice use-case though.... It might be interesting enough for me to at least start and tackle it.
BUT... as a general thing... you should perhaps not run 2 different mdns services (this and bonjour) on the same computer. I'm not sure it will ever work as expected.

**Comment by auchenberg** [comment]
Yeah, the idea is to use [MDNS to expose node-inspector instances on the network](https://github.com/node-inspector/node-inspector/pull/515), so you easily can remote debug node apps via tools like [Chrome DevTools App](https://github.com/auchenberg/chrome-devtools-app). Right now the PR is blocked by the binary dependencies of node-mdns, which I why I want to switch to a pure js implementation like yours.

**Comment by djMax** [comment]
I also want to switch to the pure mdns-js, but I have what seems to be the inverse problem. I have a service called "bridge" which is found properly by the mDns module and Bonjour Browser, but not by mdns-js... Still digging.

**Comment by kmpm** [comment]
@djMax, please file that as a separate bug.

**Comment by tberthe** [comment]
It seems that the sending port for an answer must be 5353 to be compliant with tools like avahi. Here is the kind of messages I found in `/var/log/syslog`:
```
May 22 16:47:46 raspberrypi-js avahi-daemon[2150]: Received response from host 10.80.10.23 with invalid source port 44972 on interface 'eth0.0'
```

**Comment by kmpm** [comment]
@tberthe, if that's the case it will NEVER work with 2 separate services since only one at a time can bind to 5353.
Then you will need a library that can talk to the already running service like that lovely node-mdns with all it's dependencies.

**Comment by tberthe** [comment]
It is not a problem with linux since the UDP sockets can be shared. But i don't know if it can work with windows ...
I'm currently working on modifications of node-mdns-js and have been able to run 3 applications using the port 5353 at the same time (avahi-daemon, node running a browser and node running an advertiser).
NB: Having many responders on the same machine is allowed but not recommended by the RFC. https://tools.ietf.org/html/rfc6762#section-15
https://tools.ietf.org/html/rfc6762#section-15.4

**Comment by kmpm** [comment]
Replaced by #45
