### ISSUE TITLE
Service with specific name can't be found by mdns-js, but can with mdns

### ISSUE THREAD

**Issue by djMax** [kmpm/node-mdns-js#34]
I have a service called "bridge" (_bridge._tcp) which is found with mdns browser:

````
    this.browser = mdns.createBrowser(mdns.tcp('bridge'));
````

But not with mdns-js module (same code). Here's the packet that goes out:

````
mdns:outbound message +0ms 000001000001000000000000075f627269646765045f746370056c6f63616c00000c0001
````

**Comment by notthetup** [comment]
I'm seeing the same. I managed to capture the query packets between the two. The first packet is from mdns module and the second is mdns-js module.

The main difference as far as I can see are.

https://dl.dropboxusercontent.com/u/957/mdns-compare.pcapng

1. mdns-js sets the recursive query flag (don't see this being an issue)
2. mdns-js sends the query packet from a 50xxx port (src port), while mdns always sends it from 5353.

**Comment by notthetup** [comment]
I'm beginning to think this has to do something with the fact that I'm on OSX and OSX runs bonjour in the background.

I added `mdns.excludeInterface('0.0.0.0');` but that doesn't seem to fix things.

**Comment by gregorym** [comment]
Any update?

**Comment by kmpm** [comment]
Running multiple services at the same time (mdns-js and bonjour) listening on the same port on the same IP will most likely not work.... (as stated in the README).
Could you please stop bonjour for a while and see if you get the same?
and please... I would love to get that package capture and do some comparison. It's no longer available in your dropbox it seems.

**Comment by notthetup** [comment]
Thanks @kmpm. I have since moved to using https://github.com/mafintosh/multicast-dns which worked for my use case. You're probably right though, about having bonjour running (which OSX has all the time). But it was interesting that multicast-dns package didn't have any issues.

I tore down the setup I was using for the pcaps, but I'll try to dig up the old pcaps.

**Comment by kmpm** [comment]
Replaced by #45
